### ISSUE TITLE
Wrong pattern for Parameter ServerCorsOrigin

### ISSUE THREAD

**Issue by amliuyong** [awslabs/clickstream-analytics-on-aws#127]
## Summary

Wrong pattern for Parameter ServerCorsOrigin

I want to set  `ServerCorsOrigin`  to `http://xxx.cloudfront.net`

get cloudformation error 
```
Parameter ServerCorsOrigin failed to satisfy constraint: ServerCorsOrigin must match pattern ^$|\*$|^([a-z0-9A-Z#$&@_%~\*\.\-]+\.[a-zA-Z0-9]{2,6}(,\s*[a-z0-9A-Z#$&@_%~\*\.\-]+\.[a-zA-Z0-9]{2,6})*)$
```

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
The domain for CORS should be domain name only.

But it should allow the port for the site.

**Comment by amliuyong** [comment]
I get below error when change the `access-control-allow-origin` to `d3mpqdtjegq8im.cloudfront.net`

![image](https://github.com/awslabs/clickstream-analytics-on-aws/assets/23469402/44144139-f763-46ed-902d-260007a2b0a3)

![image](https://github.com/awslabs/clickstream-analytics-on-aws/assets/23469402/461b28f1-fe5b-4737-bdf5-ec09b5bd2933)

**Comment by zxkane** [comment]
Let's look into this with priority. More similar reports are related to it.
