### ISSUE TITLE
Additional Settings typo

### ISSUE THREAD

**Issue by zhu-xiaowei** [awslabs/clickstream-analytics-on-aws#130]
## Summary

`Addtional Settings`  should be `Additional Settings` in Data ingestion module

## What is the current bug behavior?
Title text has a typo

## Relevant logs and/or screenshots

![image](https://github.com/awslabs/clickstream-analytics-on-aws/assets/33129495/d6630369-7228-4e00-9d82-30577a90a6a0)

## Possible fixes

---

This is :bug: Bug Report

**Comment by tyyzqmf** [comment]
fixed: [commit e713768](https://github.com/awslabs/clickstream-analytics-on-aws/commit/e7137681e0e00cc8ab56163e4516042d9bdc68b9#diff-288cc80fd82f3a272732993674872c4b24a919f69ea50259359e96eb8fc10263L232)
