### ISSUE TITLE
Lack of authorization to update pipeline

### ISSUE THREAD

**Issue by luorobin-a2z** [awslabs/clickstream-analytics-on-aws#133]
## Summary

when update pipeline, data modeling stack failed
![image](https://github.com/awslabs/clickstream-analytics-on-aws/assets/95616569/d2b1d354-950b-4afd-a769-448b679823c3)

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
What’s the version of pipeline?
