### ISSUE TITLE
Internal Server error when configuring pipeline 

### ISSUE THREAD

**Issue by jegansomasundar** [awslabs/clickstream-analytics-on-aws#1538]
## Summary

After the Click Stream Project is created, When configuring the Pipeline and provide all information and select only the Pipeline ingestion module alone, Error coming as Internal Server Error. 

This error is happening in the  (SO0219) Clickstream Analytics on AWS (Version v1.1.6)(Build 202406280046) . But the error doesn't come in the older version (SO0219) Clickstream Analytics on AWS (Version v1.1.5)(Build 202403071513)

## What is the current bug behavior?

Internal Server Error 

## Relevant logs and/or screenshots

[1 (1).pdf](https://github.com/user-attachments/files/16236210/1.1.pdf)

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
@jegansomasundar could you search the resource with `ApiFunction68` in your console stack, then check the verbose CloudWatch logs of the Lambda function?

<img width="923" alt="image" src="https://github.com/user-attachments/assets/57b3bb35-ee29-465f-b90a-328407f895c2">

**Comment by zxkane** [comment]
@jegansomasundar I didn't hear back from you. If it's still an issue, please follow [this guide](https://awslabs.github.io/clickstream-analytics-on-aws/en/1.2.x/troubleshooting/#problem-encountering-internal-server-error-in-the-solution-web-console) to provide the verbose log.

**Comment by jegansomasundar** [comment]
@zxkane  - Sorry for late response . Please find the lambda function response here 

`{
    "time": "2024-09-11T09:44:04.965Z",
    "type": "platform.report",
    "record": {
        "requestId": "11f7bb25-a81f-4b02-b27f-f8e6f2f2a2f6",
        "metrics": {
            "durationMs": 340.204,
            "billedDurationMs": 341,
            "memorySizeMB": 512,
            "maxMemoryUsedMB": 279
        },
        "tracing": {
            "type": "X-Amzn-Trace-Id",
            "value": "Root=1-66e16664-18b8d24d5301aca113e8ec55;Parent=5cf70e0f2cf43dd5;Sampled=1;Lineage=1:87bdc37f:0"
        },
        "spans": [
            {
                "name": "extensionOverhead",
                "start": "2024-09-11T09:44:04.964Z",
                "durationMs": 0.005
            }
        ],
        "status": "success"
    }
}`

**Comment by zxkane** [comment]
@jegansomasundar The message did not contain any error. Could you search the log context to find the message with **ERROR** level?

> @zxkane - Sorry for late response . Please find the lambda function response here
> 
> `{ "time": "2024-09-11T09:44:04.965Z", "type": "platform.report", "record": { "requestId": "11f7bb25-a81f-4b02-b27f-f8e6f2f2a2f6", "metrics": { "durationMs": 340.204, "billedDurationMs": 341, "memorySizeMB": 512, "maxMemoryUsedMB": 279 }, "tracing": { "type": "X-Amzn-Trace-Id", "value": "Root=1-66e16664-18b8d24d5301aca113e8ec55;Parent=5cf70e0f2cf43dd5;Sampled=1;Lineage=1:87bdc37f:0" }, "spans": [ { "name": "extensionOverhead", "start": "2024-09-11T09:44:04.964Z", "durationMs": 0.005 } ], "status": "success" } }`
