### ISSUE TITLE
Control plane doesn't show "Upgrade" button for pipeline

### ISSUE THREAD

**Issue by jingnanl** [awslabs/clickstream-analytics-on-aws#181]
## Summary

After upgrading the Clickstream template via CloudFormation, control plane website doesn't show "Upgrade" button for a pipeline which was created in an older version.

## Steps to reproduce

1. Create a pipeline in the version `v1.0.2-202308290112-d1be419e`
2. Upgrade Clickstream using [template](https://aws-gcr-solutions.s3.amazonaws.com/clickstream-analytics-on-aws/v1.0.2-202308291429-59fbd0c8/default/cloudfront-s3-control-plane-stack-global.template.json) via CloudFormation
3. In the control plane website, confirm the new version:`Version: v1.0.2-202308291429-59fbd0c8`.

## What is the current bug behavior?

Check the pipeline created in step 1, there is no "Upgrade" button. 

## What is the expected correct behavior?

There should be a "Upgrade" button since the pipeline version and solution version are different.

## Relevant logs and/or screenshots

![Screenshot 2023-08-30 at 09 53 19](https://github.com/awslabs/clickstream-analytics-on-aws/assets/10954206/5a6e1aa1-14cf-4397-b07c-7e7197c94f96)

## Possible fixes

---

This is :bug: Bug Report

**Comment by tyyzqmf** [comment]
Failed pipeline don't display the upgrade button
