### ISSUE TITLE
Pipeline update and rollback failed with DataProcessing error in BJS region

### ISSUE THREAD

**Issue by zhu-xiaowei** [awslabs/clickstream-analytics-on-aws#186]
## Summary
Pipeline update and rollback failed with DataProcessing error, and click `Retry` button also doesn't work.

Environment: 
BJS Region + OIDC(keycloak) + (S3, Athena only)

## Steps to reproduce
Create pipeline with above environment in `v1.0.0` then update the control plane to `v1.0.2` and update the pipeline, the error will occur.

## What is the current bug behavior?
Pipeline update failed and retry also failed.

## What is the expected correct behavior?
Pipeline can be update from v1.0.0 to v1.0.2

## Relevant logs and/or screenshots
 
<img width="1104" alt="截屏2023-08-30 19 21 32" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/33129495/49b9fd31-09c4-411c-b3e6-d6a825564819">
 
<img width="2560" alt="截屏2023-08-30 19 19 14" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/33129495/62d2ed81-d9fb-420c-8b70-6fd2dcd89bdd">
<img width="2560" alt="截屏2023-08-30 19 21 06" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/33129495/9f5b430b-1951-4f3a-b8a7-32e618e2c3dd">

## Possible fixes

This is :bug: Bug Report

**Comment by zxkane** [comment]
Duplicated with #60 

As a workaround, tuning the longer interval for data processing ensures no running EMR jobs before upgrading it.
