### ISSUE TITLE
New created ECS cluster uses old ECS task defination  

### ISSUE THREAD

**Issue by amliuyong** [awslabs/clickstream-analytics-on-aws#192]
## Summary

I created a new pipeline from control-plan, checkout the ECS cluster service, it used old task definition created before

 
<img width="1147" alt="image" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/23469402/f1ecfa18-c9e9-43cf-8a85-651e52e56145">

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
Could you check the build number of pipeline in web console? Is it the expected one?

**Comment by zxkane** [comment]
@amliuyong could you reproduce it again?

**Comment by zxkane** [comment]
No response. Free to reopen it if you still have issue.
