### ISSUE TITLE
QuickSight dashboard - Engagement: time unit is incorrect

### ISSUE THREAD

**Issue by jingnanl** [awslabs/clickstream-analytics-on-aws#240]
## Summary

In the Engagement tab of QuickSight dashboard, the "Average engagement time per user" and "Session engagement time (min)" doesn't look correct.

## Steps to reproduce

Test with Clickstream WeChat SDK and send events to ingestion server. Check QuickSight dashboard Engagement tab.

## What is the current bug behavior?

The time is being calculated in the wrong unit.

## What is the expected correct behavior?

The source data sent by WeChat SDK is using millisecond. Also confirmed that Web SDK is also using millisecond as time unit.

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
@zhu-xiaowei / @amliuyong could you confirm the unit of engagement time in data model? Is it milliseconds or minutes?

**Comment by zhu-xiaowei** [comment]
The engagement time unit in the data model is milliseconds, QuickSight will create a minute unit attribute through the calculated field, eg., (engagement_time/60/1000)

**Comment by jingnanl** [comment]
I'm validating the source data sent from WeChat SDK.

**Comment by jingnanl** [comment]
The dashboard Engagement metrics looks correct after cleaning up previous test data and retry on the demo mini program.
