### ISSUE TITLE
insufficient permission when creating ingestion server without existing service link role of AGA

### ISSUE THREAD

**Issue by zxkane** [awslabs/clickstream-analytics-on-aws#259]
## Summary

fail to create ingestion server with insufficient permission

## Steps to reproduce

1. create a project
2. create an ingestion server with AGA

## Relevant logs and/or screenshots

> Resource handler returned message: "User: arn:aws:sts::123456789012:assumed-role/xxx-clickstream-ClickStreamApiStackActio-1K5K4UTZSFHVA/gcr-solutions-clickstream-ClickStreamApiStackActio-l2PreoxogsBW is not authorized to perform: iam:CreateServiceLinkedRole on resource: arn:aws:iam::123456789012:role/aws-service-role/globalaccelerator.amazonaws.com/AWSServiceRoleForGlobalAccelerator because no identity-based policy allows the iam:CreateServiceLinkedRole action

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
Might @jingnanl have a try?

**Comment by jingnanl** [comment]
I tried to reproduce the issue in local but didn't see the problem. I used the latest build and created a pipeline with an ingestion server which enabled Global Accelerator in ap-southeast-1 successfully. Did I miss any configuration to reproduce the issue?

**Comment by zxkane** [comment]
You need make sure there is no IAM service link role for global accelerator. Delete it if you already have the role in your account.
