### ISSUE TITLE
updating the existing pipeline CORS does not work

### ISSUE THREAD

**Issue by zhu-xiaowei** [awslabs/clickstream-analytics-on-aws#26]
## Summary

Modify pipeline CORS settings to `*` is not work. 

## Steps to reproduce
1. modify a pipeline which is not set the CORS, then leave the '*' and update pipeline
2. wait the pipeline status to be active
3. send the request by endpoint 
4. the CORS error will appear with no `Access-Control-Allow-Origin` header

## What is the current bug behavior?
<img width="1321" alt="截屏2023-07-13 09 38 38" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/33129495/b754cfa8-e472-4d07-87b2-aab1af998ef7">

## What is the expected correct behavior?
Send the request success

## Possible fixes
Create a new pipeline with CORS `*` is works, it seems to update the pipeline issue.

---

This is :bug: Bug Report

**Comment by dengmingtong** [comment]
Ingestion server support updating CORS, the reason of the error is the pipeline version is too old, cannot support updating through control plane directly.
@tyyzqmf  please confirm it.

**Comment by zxkane** [comment]
it's already fixed in a89d72e488
