### ISSUE TITLE
Spark ETL job failed with no space left on device error 

### ISSUE THREAD

**Issue by zhu-xiaowei** [awslabs/clickstream-analytics-on-aws#275]
## Summary

When sending more than 20 million events in 30 minutes, Spark ETL job will failed with error: 
> java.io.IOException: No space left on device

## Steps to reproduce
1. create pipeline with workshop configuration
2. using python script and sending e-commerce events with 10000 user and generate last 30 days events.

## What is the current bug behavior?
ETL job fails, no events are successfully loaded into Redshift.

## What is the expected correct behavior?
ETL job success, and all event are load to Redshift.

## Relevant logs and/or screenshots

<img width="1138" alt="截屏2023-10-07 15 04 07" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/33129495/df356dbb-c972-44ab-bee9-a8e9a0e78ff4">

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
@amliuyong It probably need more resources for spliting raw events to four dimension tables.

**Comment by zxkane** [comment]
The new example shopping data is larger than the notepad example data, which is the cause of it. The default EMR configuration cannot handle as many volumes of events with the notepad data.

You can follow up [this doc](https://awslabs.github.io/clickstream-analytics-on-aws/en/pipeline-mgmt/data-processing/configure-execution-para/#config-spark-job-parameters) to increase the cluster capability to process large data volume.

**Comment by zxkane** [comment]
Anyway, we will re-benchmark the data processing program to be as tuned as possible.

**Comment by zxkane** [comment]
It's caused by the default cluster resource, which cannot process the volume of data.

Please follow up on [this troubleshooting guide](https://awslabs.github.io/clickstream-analytics-on-aws/en/latest/troubleshooting/#problem-data-processing-job-failure) to increase the Spark cluster resource.
