### ISSUE TITLE
Failed to register new application due to invalid request id

### ISSUE THREAD

**Issue by jingnanl** [awslabs/clickstream-analytics-on-aws#304]
## Summary

It failed to register app after creating a new pipeline. The `/api/app` returns 400 bad request.

## Steps to reproduce

1. Create a new pipeline (in demo account)
2. Register a new app

## What is the current bug behavior?

POST https:/the-server/api/app returns 400 Bad Request.
```
{
    "success": false,
    "message": "Parameter verification failed.",
    "error": [
        {
            "value": "xxxxxxxxxxxxxxxxxx",
            "msg": "Not Modified.",
            "param": "x-click-stream-request-id",
            "location": "headers"
        }
    ]
}
```

## What is the expected correct behavior?

It should register the app successfully.

## Possible fixes

It looks like the app request id is invalid.
 **X-Click-Stream-Request-Id: xxxxxxxxxxxxxxxxxx**.

---

This is :bug: Bug Report

**Comment by jingnanl** [comment]
I checked the **click-stream-control-plane-ClickStreamApiClickstreamMetadata** table, `type=REQUESTID`, the ID's are all like `mmmmmmmmmmmmmmmmmm` and `hhhhhhhhhhhhhhhhhh`. Delete all the IDs and retry, this time it succeeded.

**Comment by zxkane** [comment]
Can you reproduce it with certain steps?

**Comment by jingnanl** [comment]
> Can you reproduce it with certain steps?

It seems not rare. I saw this error not only in app register, but also in other steps of pipeline creation.
