### ISSUE TITLE
validate the existing NAT gateway configuration before creating pipeline

### ISSUE THREAD

**Issue by zhu-xiaowei** [awslabs/clickstream-analytics-on-aws#357]
## Summary
When creating a data pipeline, we should check if the NAT is in a public subnet.

## Steps to reproduce
Select an VPC which have an NAT in private subnet and create pipeline, the pipeline will create failed.

## What is the current bug behavior?
The DataProcessing stack created failed with socket timed out error.

## What is the expected correct behavior?
Pipeline create success.

## Relevant logs and/or screenshots
Received response status [FAILED] from custom resource. Message returned: Socket timed out without establishing a connection within 5000 ms Logs: /aws/lambda/Clickstream-DataProcessin-GlueTablePartitionSyncer-xxx at Timeout._onTimeout

## Possible fixes
Check the NAT whether in publish subnet when create pipeline.

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
It's similar to #88 in that it validates the misconfiguration network that prevents access to the AWS service endpoints.

**Comment by zxkane** [comment]
closed by #446
