### ISSUE TITLE
can't properly delete stack: Clickstream-DataModelingRedshift-xxxxx-NewServerlessRedshiftNestedStackNewServerl-xxxx

### ISSUE THREAD

**Issue by qianyangcassie** [awslabs/clickstream-analytics-on-aws#360]
## Summary

when deleting nested stack Clickstream-DataModelingRedshift-xxxxx-NewServerlessRedshiftNestedStackNewServerl-xxxx, there will be error: esource sg-xxxxxx has a dependent object (Service: AmazonEC2; Status Code: 400; Error Code: DependencyViolation; 

## Steps to reproduce

delete project from clickstream console, then we can find that nested stack Clickstream-DataModelingRedshift-xxxxx-NewServerlessRedshiftNestedStackNewServerl-xxxx failed

## What is the current bug behavior?

can't properly delete stack: Clickstream-DataModelingRedshift-xxxxx-NewServerlessRedshiftNestedStackNewServerl-xxxx

## What is the expected correct behavior?

 stack: Clickstream-DataModelingRedshift-xxxxx-NewServerlessRedshiftNestedStackNewServerl-xxxx can be deleted properly 

## Relevant logs and/or screenshots

<img width="929" alt="Screenshot 2023-10-25 at 14 59 41" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/21259655/ea5994b0-5135-4c78-80fc-1335e4afe1a8">

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
Could you check if the security group `sg-xxxxxx` was changed out of the stack?

**Comment by qianyangcassie** [comment]
it's created by stack and isn't been changed
![Uploading Screenshot 2023-10-26 at 17.10.50.png…]()

**Comment by dengmingtong** [comment]
Cannot reproduce this issue in my env, wait for qianyang to confirm it.
