### ISSUE TITLE
when deleting project, sub stack fail to delete due to no authorization

### ISSUE THREAD

**Issue by qianyangcassie** [awslabs/clickstream-analytics-on-aws#384]
## Summary

when deleting project, sub stack fail to delete due to no authorization： 
"User: arn:aws:sts::xxxxxx:assumed-role/tCaT-cs-cloudfront-s3-t2--ClickStreamApiStackAction-msaJADhAkLqY/tCaT-cs-cloudfront-s3-t2--ClickStreamApiStackActio-VgjIrk2fMLIM is not authorized to perform: redshift-serverless:GetWorkgroup on resource: arn:aws:redshift-serverless:ap-northeast-2:xxxxxx:workgroup/3d89f754-e3d0-40ea-b862-976bebd967dc because no identity-based policy allows the redshift-serverless:GetWorkgroup action (Service: RedshiftServerless, Status Code: 400, Request ID: 3ea613f9-2e6b-4a3d-9363-aaff67009dc2)"

## Steps to reproduce

1. create project and create pipeline
2. After pipeline active, delete project 

## What is the current bug behavior?

check the sub stacks status, we find that the sub stacks fail to delete 

## What is the expected correct behavior?

the sub stacks are deleted successfully

## Relevant logs and/or screenshots

![Screenshot 2023-10-30 at 22 25 00](https://github.com/awslabs/clickstream-analytics-on-aws/assets/21259655/fba4c3b1-7cbd-43b2-b079-449d1c5797a1)

## Possible fixes

---

This is :bug: Bug Report

**Comment by tyyzqmf** [comment]
May be the reason is **control plane stack** was already deleted when deleting the sub stack.

**Comment by zxkane** [comment]
@qianyangcassie could you confirm if it's reproducible? We have a [troubleshoot problem](https://awslabs.github.io/clickstream-analytics-on-aws/en/latest/troubleshooting/#problem-can-not-delete-the-cloudformation-stacks-created-for-the-clickstream-pipeline) might help it.

**Comment by zxkane** [comment]
No response. Free to reopen it if you still have issue.
