### ISSUE TITLE
No error when do not select transform plugin when use Third party SDK

### ISSUE THREAD

**Issue by amliuyong** [awslabs/clickstream-analytics-on-aws#462]
## Summary

Test case: 

EXPECTED: if user select the SDK type as Third party and do not select the transform plugin, there will be error.

ACTUAL: I can go next, no error

![image](https://github.com/awslabs/clickstream-analytics-on-aws/assets/23469402/e6c13706-1448-4ba2-9b63-9292a5ad5b1b)

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
duplicated with #55
