### ISSUE TITLE
Reporting stack cannot be upgraded after control plane update.

### ISSUE THREAD

**Issue by dengmingtong** [awslabs/clickstream-analytics-on-aws#468]
## Summary

Reporting stack cannot be upgraded after control plane update.

## Steps to reproduce

1. Update control plane by version (Version v1.1.0)(Build dev-main-202311101512-333415db)

## What is the current bug behavior?

Reporting stack cannot be triggered to update.
The pipeline status in control plane is Warning.
<img width="1325" alt="Screenshot 2023-11-12 at 16 54 32" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/8953013/0d87e49a-bbda-48eb-be02-79d88082a830">

Error log in Step function ClickStreamApiStackActionStateMachine workflow:

```
{
  "errorType": "Error",
  "errorMessage": "Parameters: [QuickSightOwnerPrincipalParam] must have values",
  "trace": [
    "Error: Parameters: [QuickSightOwnerPrincipalParam] must have values",
    "    at upgradeStack (/var/task/index.js:56477:11)",
    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
  ]
}
```

## What is the expected correct behavior?

Reporting stack can be triggered to update.

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
closed as completed
