### ISSUE TITLE
No error when select invalid Data processing interval and Event freshness

### ISSUE THREAD

**Issue by amliuyong** [awslabs/clickstream-analytics-on-aws#527]
## Steps to reproduce
when I select the negative integer value, there are no errors.

![image](https://github.com/awslabs/clickstream-analytics-on-aws/assets/23469402/eb0da72a-ec49-4c47-9304-b1ad891f0f9f)

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
Could you submit the invalid interval?
