### ISSUE TITLE
No error when I select 3 subnets in 2 Azs when deploying redshift

### ISSUE THREAD

**Issue by amliuyong** [awslabs/clickstream-analytics-on-aws#528]
## Steps to reproduce
![image](https://github.com/awslabs/clickstream-analytics-on-aws/assets/23469402/ae09d5f8-9765-42d7-aab8-accdef7e60c0)

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
Duplicated with #463
