### ISSUE TITLE
Transformation name is not shown in the control plane

### ISSUE THREAD

**Issue by amliuyong** [awslabs/clickstream-analytics-on-aws#529]
## Steps to reproduce
![image](https://github.com/awslabs/clickstream-analytics-on-aws/assets/23469402/aa4f580f-deab-42a6-97cc-7ec5f9aa1a0d)

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
Current design is not showing transformer for built-in one. GTM is another kind of builtin even it’s a third party transformer.

**Comment by zxkane** [comment]
Please check if there's still an issue with the latest version.
