### ISSUE TITLE
Improve Powertools Logger usage

### ISSUE THREAD

**Issue by am29d** [awslabs/clickstream-analytics-on-aws#534]
## :question: General Issue

Hi, I am one of the maintainer of powertools-lambda-typescript projects. I have stumbled upon the project and noticed that you use powertools logger and metrics extensively, thank a lot 🙏. I hope powertools improves your observability and is of great help in navigating through logs and metrics. 

I have noticed that there are some cases where we could further improve powertools usage in the project and hope this can be valuable for you. These are really small issues, but as a sum could overall be improvement for the future. 

**Remove unnecessary event logging**: you have [configured](https://github.com/awslabs/clickstream-analytics-on-aws/blob/19651cdece5cfa000f30be57b1a4540ebb317e0f/src/common/powertools.ts#L18) `POWERTOOLS_LOGGER_LOG_EVENT` as `true` in your commons package. This means that powertools will log lambda invocation events automatically. There are several cases where we log lambda events additionally, i.e. [here](https://github.com/awslabs/clickstream-analytics-on-aws/blob/19651cdece5cfa000f30be57b1a4540ebb317e0f/src/control-plane/backend/lambda/sfn-workflow/index.ts#L45). We could remove this lines and simplify our code further

**Remove `JSON.stringify()` in logger**: Powertools Logger has many features and one of them is to accept objects. Instead of calling `JSON.stringify()` you can pass entire object: 

```ts
// before
logger.info('requestJson:', JSON.stringify(event, undefined, 2));
// after
logger.info('request arrived:` , {event});
```

**Inject Lambda context**: Lambda context contains function name, arn, cold start, function size, memory and request, which is helpful when troubleshooting issues and filtering logs. With additional method `logger.addContext(context)` we could add this information for free into the log structure of our Lambda functions. 

**Add tracer**: I see that you use a lot of SDK clients which we could easily add to x-ray using powertools tracer. This would improve visibility into the processing requests and highlight observability capabilities into a complex system. 

I am happy to work on these topics and contribute these changes in a dedicated PR, if you think this is helpful for the project. Let me know what you think.

**Comment by zxkane** [comment]
@am29d Alex, thanks for the helpful information. The team is working on other stuff now, and we must wait a while to prioritize it. Any PR is appreciated. 🙏🏼

**Comment by am29d** [comment]
@zxkane completely understand, I will be more than happy to contribute.
