### ISSUE TITLE
Delete App failed with error "The current pipeline status does not allow update"

### ISSUE THREAD

**Issue by zhu-xiaowei** [awslabs/clickstream-analytics-on-aws#56]
## Summary
create a app and upload past 30 days events, and current pipeline status is `Active` in control plane and cloudformation, when click delete button it shows the error: "The current pipeline status does not allow update"

## Steps to reproduce
1. create a pipeline 
2. create a app
3. upload last 30 days events using `standalone-data-generator` python script
4. select the app, and click delete button 
5. the error shows

## What is the current bug behavior?
Can't delete the app which have already have some events, but the app which have no events, can be deleted expected.

## What is the expected correct behavior?
The app can be delete successfully

## Relevant logs and/or screenshots
<img width="1596" alt="截屏2023-07-19 09 10 56" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/33129495/570a8698-4b00-44c0-99ea-ade8cf3eed17">
<img width="2316" alt="image" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/33129495/d57e3a2f-3203-4ca6-b95d-c0d19e4dab52">

## Possible fixes

---

This is :bug: Bug Report

**Comment by zhu-xiaowei** [comment]
After about 20 minutes, click delete button, the page will refresh with no error, and the app still in the list, then delete twice the app can be delete. What's the prerequisites for delete a app?

**Comment by zxkane** [comment]
It's already fixed in v1.1.0, which does not allow to delete the `CREATING` or `UPDATING` pipeline.
