### ISSUE TITLE
[UI] Pipeline details page doesn't reflect correct stack status while updating pipeline

### ISSUE THREAD

**Issue by jingnanl** [awslabs/clickstream-analytics-on-aws#569]
## Summary

Pipeline details page doesn't reflect correct stack status while updating pipeline

## Steps to reproduce

1. Deploy v1.0.3 control plane
2. Create pipeline in v1.0.3
3. Upgrade control plane to v1.1.0
4. Upgrade existing pipeline to v1.1.0

## What is the current bug behavior?

During updating, the pipeline stacks status in the project page is correct, while the status shown in the pipeline details page is incorrect.

Status in project page:
<img width="1276" alt="image" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/10954206/05ebf6cc-457c-48ca-8a48-db062b3ec41a">

Status in pipeline details page:
<img width="1298" alt="image" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/10954206/1c57496a-1df4-43b4-86a0-a7169157645f">

## What is the expected correct behavior?

The pipeline details page should show correct stacks status.

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
Please check if there's still an issue with the latest version.

**Comment by jingnanl** [comment]
Didn't reproduce the issue with the latest version. Close the issue.
