### ISSUE TITLE
Pipeline deletion failed while app deletion is ongoing

### ISSUE THREAD

**Issue by jingnanl** [awslabs/clickstream-analytics-on-aws#573]
## Summary

Failed to delete pipeline after deleting app from control plane website.

## Steps to reproduce

1. Create pipeline and add an app, wait until pipeline status is Active.
2. Delete app.
3. Delete pipeline immediately after app deletion was kicked off in the last step.

## What is the current bug behavior?

1. Pipeline deletion failed. 
2. In DDB metadata table, the pipeline status is deleted, while the Cfn stacks still exist.

## What is the expected correct behavior?

Both app and pipeline deletion should succeed.

## Relevant logs and/or screenshots

> Error: Stack:arn:aws-cn:cloudformation:cn-north-1:259558890137:stack/Clickstream-DataModelingRedshift-e6a7d4dac2e042e5a064ff88f91d3e34/9017a4f0-8cd7-11ee-b2cd-0213d5354620 is in DELETE_IN_PROGRESS state and can not be updated.

> Error: Stack [arn:aws-cn:cloudformation:cn-north-1:259558890137:stack/Clickstream-Ingestion-kinesis-e6a7d4dac2e042e5a064ff88f91d3e34/e44b63a0-8cd6-11ee-a287-066d4e92294c] cannot be deleted while in status UPDATE_IN_PROGRESS

## Possible fixes

Check pipeline status in both frontend and backend before deletion, wait until pipeline status is Active.

---

This is :bug: Bug Report

**Comment by tyyzqmf** [comment]
fixed: https://github.com/awslabs/clickstream-analytics-on-aws/pull/584/files#diff-33aa21ba0b1b80ac7111debef50530d31e4cb198397165dde138d7046bb7f3c0R268-R269
