### ISSUE TITLE
pipeline upgrade fail due to EMR in STARTED status

### ISSUE THREAD

**Issue by llmin** [awslabs/clickstream-analytics-on-aws#59]
## Summary

when upgrade pipeline from 1.0.0 to 1.0.1 , data process stack fails.

## Steps to reproduce

1. update control plane
2. select target pipeline to upgrade
3. click 'upgrade' button 

## What is the current bug behavior?

stack can upgrade successfully

## Possible fixes

---

This is :bug: Bug Report

**Comment by llmin** [comment]
![截屏2023-07-19 10 39 07](https://github.com/awslabs/clickstream-analytics-on-aws/assets/32735839/c0f04757-4240-4570-abb5-ce7812500262)

**Comment by zxkane** [comment]
duplicated #60
