### ISSUE TITLE
[UI] When creating/updating pipeline, user can still click next and save pipeline when adding invalid tags

### ISSUE THREAD

**Issue by jingnanl** [awslabs/clickstream-analytics-on-aws#883]
## Summary

When creating/updating pipeline, user can still click next and save pipeline when adding invalid tags, although there is error message in the UI. As an improvement, we may want to disable "Next" button when there is any invalid input.

## Steps to reproduce

1. Create pipeline
2. Input invalid tags in the first step (the error message should show up)
3. Click "Next" button

## What is the current bug behavior?

User can save the pipeline, and the action is likely to fail due to invalid tags.

## What is the expected correct behavior?

Disable "Next" button until all the input is valid.

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
Is it fixed in #881?

**Comment by zxkane** [comment]
Please check if there's still an issue with the latest version.

**Comment by jingnanl** [comment]
If user inputs duplicated tag, they can still go to next step despite the UI warning.
