### ISSUE TITLE
Delete reporting stack fails when deleting two apps

### ISSUE THREAD

**Issue by zhu-xiaowei** [awslabs/clickstream-analytics-on-aws#934]
## Summary
Delete reporting stack fails when deleting two apps

## Steps to reproduce
1. create pipeline with reporting
2. create two apps and send example data
3. delete the first app then delete the second app quickly

## What is the current bug behavior?
1. the reporting stack deleted failed.

## What is the expected correct behavior?
stack successfully deleted

## Relevant logs and/or screenshots
<img width="2449" alt="image" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/33129495/c1192258-5258-47f4-8ff4-702837bcecb0">

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
In mainline, the console already prevents another updating operation if an operation is running.
