### ISSUE TITLE
optimize the backend build

### ISSUE THREAD

**Issue by zxkane** [awslabs/clickstream-analytics-on-aws#95]
## Describe the feature

- [ ] use the built aws-lambda-web-adapter to speed up the build
- [ ] move the backend build Dockerfile in the src/control-plane 

## Other Information

**Notes**:

- [ ] this feature has an UI update
- [ ] this feature contains an implementation guide update

---

**Comment by tyyzqmf** [comment]
can not  move the backend build Dockerfile in the src/control-plane, because the **docker build content** needs to include the original file of the soft link, otherwise the file will not be found.
